[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
  "cd backend",
  "dotnet restore NotesAPI/NotesAPI.csproj",
  "dotnet publish NotesAPI/NotesAPI.csproj -c Release -o out"
]

[start]
cmd = "cd backend && dotnet ./out/NotesAPI.dll"
