[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
  "cd backend/NotesAPI",
  "dotnet restore NotesAPI.csproj",
  "dotnet publish NotesAPI.csproj -c Release -o out"
]

[start]
cmd = "cd backend/NotesAPI && dotnet ./out/NotesAPI.dll"
